import OpenAI from "openai";
import { SYSTEM_PROMPT, createUserPrompt } from "../prompts.js";

export class OpenAIService {
  private client: OpenAI;

  constructor(apiKey: string) {
    this.client = new OpenAI({ apiKey });
  }

  async generateRoast(stats: { additions: number; deletions: number; changedFiles: number }, diff: any): Promise<string> {
    const completion = await this.client.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: SYSTEM_PROMPT,
        },
        {
          role: "user",
          content: createUserPrompt(stats, diff),
        },
      ],
      temperature: 0.8,
      max_tokens: 800,
    });

    const roast = completion.choices[0].message.content;
    if (!roast) {
      throw new Error("No content generated by OpenAI");
    }

    return roast;
  }
}
